<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>YModemWin.Core</RootNamespace>
    <AssemblyName>YModemWin.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Sentry" Version="6.1.0" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="System.IO.Ports" Version="10.0.3" />
    <PackageReference Include="Ymodem.Protocol" Version="0.2.0" />
  </ItemGroup>
</Project>
