<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>YModemWin</RootNamespace>
    <AssemblyName>YModem</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <UseWinUI>true</UseWinUI>
    <EnableMsixTooling>true</EnableMsixTooling>
    <WindowsPackageType>MSIX</WindowsPackageType>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
    <WindowsAppSdkBootstrapInitialize>false</WindowsAppSdkBootstrapInitialize>
<!--    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>-->
    <WindowsAppSdkDeploymentManagerInitialize>false</WindowsAppSdkDeploymentManagerInitialize>

    <PackageCertificateThumbprint>33DB6222982CF0DF47798E6338A23AA78C548519</PackageCertificateThumbprint>
<!--    <PackageCertificateKeyFile>YModemWin-MsixTest.pfx</PackageCertificateKeyFile>-->
<!--    <PackageCertificatePassword>pfx-pass</PackageCertificatePassword>-->
    <ApplicationIcon>Assets\Square256x256Logo.ico</ApplicationIcon>
    <GenerateAppInstallerFile>False</GenerateAppInstallerFile>
    <AppxPackageSigningEnabled>True</AppxPackageSigningEnabled>
    <AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
    <AppxAutoIncrementPackageRevision>True</AppxAutoIncrementPackageRevision>
    <AppxSymbolPackageEnabled>True</AppxSymbolPackageEnabled>
    <GenerateTestArtifacts>True</GenerateTestArtifacts>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.250108002" />
    <PackageReference Include="Sentry" Version="6.1.0" />
    <PackageReference Include="Sentry.Profiling" Version="6.1.0" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="DeviceProgramming" Version="1.0.8" />
    <PackageReference Include="System.IO.Ports" Version="10.0.3" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YModemWin.Core\YModemWin.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Manifest Include="Package.appxmanifest" />
    <Page Remove="Localization\*.xaml" />
    <Content Include="Localization\*.xaml" CopyToOutputDirectory="PreserveNewest" />
    <PRIResource Remove="Localization\*.xaml" />
    <Content Remove="Assets\BadgeLogo.scale-100.png" />
    <Content Remove="Assets\BadgeLogo.scale-125.png" />
    <Content Remove="Assets\BadgeLogo.scale-150.png" />
    <Content Remove="Assets\BadgeLogo.scale-200.png" />
    <Content Remove="Assets\BadgeLogo.scale-400.png" />
    <Content Remove="Assets\LargeTile.scale-100.png" />
    <Content Remove="Assets\LargeTile.scale-125.png" />
    <Content Remove="Assets\LargeTile.scale-150.png" />
    <Content Remove="Assets\LargeTile.scale-200.png" />
    <Content Remove="Assets\LargeTile.scale-400.png" />
    <Content Remove="Assets\SmallTile.scale-100.png" />
    <Content Remove="Assets\SmallTile.scale-125.png" />
    <Content Remove="Assets\SmallTile.scale-150.png" />
    <Content Remove="Assets\SmallTile.scale-200.png" />
    <Content Remove="Assets\SmallTile.scale-400.png" />
    <Content Remove="Assets\SplashScreen.scale-100.png" />
    <Content Remove="Assets\SplashScreen.scale-125.png" />
    <Content Remove="Assets\SplashScreen.scale-150.png" />
    <Content Remove="Assets\SplashScreen.scale-200.png" />
    <Content Remove="Assets\SplashScreen.scale-400.png" />

    <Content Remove="Assets\WideTile.scale-100.png" />
    <Content Remove="Assets\WideTile.scale-125.png" />
    <Content Remove="Assets\WideTile.scale-150.png" />
    <Content Remove="Assets\WideTile.scale-200.png" />
    <Content Remove="Assets\WideTile.scale-400.png" />
    <Content Remove="Assets\YModem.scale-100.png" />
    <Content Remove="Assets\YModem.scale-125.png" />
    <Content Remove="Assets\YModem.scale-150.png" />
    <Content Remove="Assets\YModem.scale-200.png" />
    <Content Remove="Assets\YModem.scale-400.png" />
    <Content Update="Localization\en-us\Strings.en-us.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Update="Localization\zh-cn\Strings.zh-cn.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>
