//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YModemWin.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YModemWin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        // Main Window
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        internal static string Baud {
            get {
                return ResourceManager.GetString("Baud", resourceCulture);
            }
        }
        
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        internal static string RefreshPorts {
            get {
                return ResourceManager.GetString("RefreshPorts", resourceCulture);
            }
        }
        
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        internal static string Receive {
            get {
                return ResourceManager.GetString("Receive", resourceCulture);
            }
        }
        
        internal static string TransferProgress {
            get {
                return ResourceManager.GetString("TransferProgress", resourceCulture);
            }
        }
        
        internal static string Idle {
            get {
                return ResourceManager.GetString("Idle", resourceCulture);
            }
        }
        
        internal static string RuntimeLogs {
            get {
                return ResourceManager.GetString("RuntimeLogs", resourceCulture);
            }
        }
        
        internal static string AutoScroll {
            get {
                return ResourceManager.GetString("AutoScroll", resourceCulture);
            }
        }
        
        internal static string ClearLogs {
            get {
                return ResourceManager.GetString("ClearLogs", resourceCulture);
            }
        }
        
        // Send Page
        internal static string AddFiles {
            get {
                return ResourceManager.GetString("AddFiles", resourceCulture);
            }
        }
        
        internal static string ParsedFiles {
            get {
                return ResourceManager.GetString("ParsedFiles", resourceCulture);
            }
        }
        
        internal static string ParsedFilesTooltip {
            get {
                return ResourceManager.GetString("ParsedFilesTooltip", resourceCulture);
            }
        }
        
        internal static string ParsedFilesDisabledTooltip {
            get {
                return ResourceManager.GetString("ParsedFilesDisabledTooltip", resourceCulture);
            }
        }
        
        internal static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }
        
        internal static string StartSend {
            get {
                return ResourceManager.GetString("StartSend", resourceCulture);
            }
        }
        
        internal static string TimeoutSec {
            get {
                return ResourceManager.GetString("TimeoutSec", resourceCulture);
            }
        }
        
        internal static string SelectFilesFirst {
            get {
                return ResourceManager.GetString("SelectFilesFirst", resourceCulture);
            }
        }
        
        // Receive Page
        internal static string SaveFolder {
            get {
                return ResourceManager.GetString("SaveFolder", resourceCulture);
            }
        }
        
        internal static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        internal static string StartReceive {
            get {
                return ResourceManager.GetString("StartReceive", resourceCulture);
            }
        }
        
        // Common
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Cancelling {
            get {
                return ResourceManager.GetString("Cancelling", resourceCulture);
            }
        }
        
        // Status Messages
        internal static string SendCanceledByUser {
            get {
                return ResourceManager.GetString("SendCanceledByUser", resourceCulture);
            }
        }
        
        internal static string ReceiveCanceledByUser {
            get {
                return ResourceManager.GetString("ReceiveCanceledByUser", resourceCulture);
            }
        }
        
        internal static string LanguageSwitched {
            get {
                return ResourceManager.GetString("LanguageSwitched", resourceCulture);
            }
        }
        
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        internal static string Telemetry {
            get {
                return ResourceManager.GetString("Telemetry", resourceCulture);
            }
        }
        
        internal static string TelemetrySwitched {
            get {
                return ResourceManager.GetString("TelemetrySwitched", resourceCulture);
            }
        }
        
        internal static string TelemetryTooltip {
            get {
                return ResourceManager.GetString("TelemetryTooltip", resourceCulture);
            }
        }
        
        internal static string PleaseSelectPort {
            get {
                return ResourceManager.GetString("PleaseSelectPort", resourceCulture);
            }
        }
        
        // Progress
        internal static string SendBytesFormat {
            get {
                return ResourceManager.GetString("SendBytesFormat", resourceCulture);
            }
        }
        
        internal static string SendPacketsFormat {
            get {
                return ResourceManager.GetString("SendPacketsFormat", resourceCulture);
            }
        }
        
        internal static string ReceiveBytesFormat {
            get {
                return ResourceManager.GetString("ReceiveBytesFormat", resourceCulture);
            }
        }
        
        internal static string ReceivePacketsFormat {
            get {
                return ResourceManager.GetString("ReceivePacketsFormat", resourceCulture);
            }
        }
    }
}
